# Peer Assessment Plan — `styloprofile`

**Armand Surbakti — 300680133**
**Repository:** <https://github.com/ArmandFS/data501_package>
The numerical core, the OO workflow, the corpus layer and the
test suite are built and passing. Section 5 below lists exactly what is still missing and why, so
nothing here is overstated.

This document exists for peer review week. It lists every function currently implemented, explains the
architecture, verifying the function, and numerous ways of testing the package. 

---

## 1. Installation guide

```r
# install.packages("remotes")
remotes::install_github("ArmandFS/data501_package")
```

Notes:

- The **repository** is named `data501_package`; the **package** it installs is named `styloprofile`.
  `library(styloprofile)` after install, not `library(data501_package)`.
- Requires **R >= 4.0**.
- The package compiles C++ via `Rcpp` (`LinkingTo: Rcpp`), so a working toolchain is needed: Xcode
  command line tools on macOS (`xcode-select --install`), Rtools on Windows (matched to the installed R
  version). `devtools::dev_sitrep()` reports whether the toolchain is set up correctly if the install
  fails at the compilation step.
- No API key or account is needed for anything in the package. The only networked function,
  `fetch_corpus()`, talks to the fully open OpenAlex API.

### Smoke test

Paste this after installing, to confirm the Rcpp code, the OO workflow and both distance methods all
work end-to-end, using the corpus bundled with the package:

```r
library(styloprofile)

## 1. the compiled Rcpp function
count_syllables_cpp(c("cat", "table", "make", "beautiful", "queue"))
#> [1] 1 2 1 3 1

## 2. the OO workflow
profile <- build_profile(lidar_reference$abstract)
#> Profile built from 245 documents on 5 features.
class(profile)
#> [1] "stylo_profile"
summary(profile)

## 3. score new documents by either distance
scores <- score(lidar_contrast$abstract, profile, method = "mahalanobis")
class(scores)
#> [1] "stylo_score"
summary(scores)

## 4. run the unit tests
testthat::test_local()
#> [ FAIL 0 | WARN 0 | SKIP 0 | PASS 142 ]
```

---

## 2. Architecture: OO design and Rcpp

### Package layout

```
styloprofile/
├── DESCRIPTION          Imports: Rcpp, stats, jsonlite, tools, utils; LinkingTo: Rcpp
├── NAMESPACE            Generated by roxygen2
├── R/
│   ├── angular.R            cosine_sim(), angular_dist()
│   ├── corpus.R             fetch_corpus(), build_oa_filter(), read_corpus_json()
│   ├── data.R               documentation for lidar_reference / lidar_contrast
│   ├── features.R           stylo_features()
│   ├── mahalanobis.R        mahalanobis_sq()
│   ├── profile.R            build_profile() + stylo_profile S3 methods
│   ├── score.R              score() + stylo_score S3 methods
│   ├── syllables.R          count_syllables_r()
│   └── RcppExports.R        Generated by Rcpp
├── src/
│   ├── count_syllables.cpp  count_syllables_cpp()
│   └── RcppExports.cpp      Generated by Rcpp
├── data/                lidar_reference.rda, lidar_contrast.rda (245 and 211 abstracts)
├── inst/extdata/        openalex_sample.json -- fixture for offline corpus tests
├── man/                 11 .Rd files, generated by roxygen2
└── tests/testthat/      5 test files, 142 passing expectations (see Section 4)
```

### Object-oriented design

Two S3 classes, each with a constructor and `print`/`summary` methods, where `summary()` itself returns
a classed object with its own `print` method -- the same structure `stats::aov()` uses.

| Class | Constructor | Methods |
|---|---|---|
| `stylo_profile` | `build_profile()` | `print.stylo_profile`, `summary.stylo_profile` |
| `summary.stylo_profile` | `summary()` | `print.summary.stylo_profile` |
| `stylo_score` | `score()` | `print.stylo_score`, `summary.stylo_score` |
| `summary.stylo_score` | `summary()` | `print.summary.stylo_score` |

`build_profile()` returns a list of class `stylo_profile` holding `center`, `scale`, `chol_cov`,
`angular_ref`, `n`, `p`, `features` and `call`. `score()` returns an object of class `stylo_score` that
deliberately subclasses a plain numeric vector, so `d >= 0`, `median(d)` and `length(d)` all still work
on it directly.

### The Rcpp call chain

```
build_profile(text) -> stylo_features() -> count_syllables_cpp()   [C++]
                                        -> .Call()                 [R/RcppExports.R]
                                        -> src/count_syllables.cpp
```

`stylo_features()` calls the compiled `count_syllables_cpp()` to compute `prop_polysyllabic`. Syllable
counting is a character-by-character scan carrying state between iterations (was the previous character
a vowel), which is the shape of problem where R's vectorisation gives nothing -- each character has to be
examined in order, and interpreter overhead per character dominates the work. Measured on 10,000 words,
20 repetitions:

| Implementation | Median time |
|---|---|
| `count_syllables_cpp()` | 1.97 ms |
| `count_syllables_r()` | 27.11 ms |

**~13.8x faster**, which is what justifies the compilation step. `count_syllables_r()` is not a fallback
-- it exists specifically to be a test oracle for the compiled version (Section 4).

---

## 3. Functions implemented

All 11 exported functions, grouped by role.

### Corpus acquisition

| Function | Signature | Purpose |
|---|---|---|
| `fetch_corpus()` | `fetch_corpus(topic, from = "2008-01-01", to = "2022-12-31", source = "S117727964", publisher = NULL, type = "article", max_n = 500L, mailto = NULL, min_words = 40L, cache_dir = NULL, refresh = FALSE, verbose = TRUE)` | Downloads abstracts from the OpenAlex API for a topic/journal/date window. **Needs internet.** No API key required -- OpenAlex is fully open; `mailto` only requests OpenAlex's faster "polite pool". Caches results to disk, so a repeat call with the same arguments does not hit the network again. |
| `build_oa_filter()` | `build_oa_filter(topic, from, to, source = "S117727964", publisher = NULL, type = "article", has_abstract = TRUE)` | Builds the OpenAlex filter string. Pure string construction, no network access. |
| `read_corpus_json()` | `read_corpus_json(path, min_words = 40L, verbose = TRUE)` | Parses a **saved** OpenAlex JSON response from disk. This is the offline-testable half of corpus acquisition -- see Section 4. |

### Feature extraction

| Function | Signature | Purpose |
|---|---|---|
| `stylo_features()` | `stylo_features(text)` | Extracts 5 stylometric features per document: `mean_sentence_length`, `conj_rate`, `cv_word_length`, `prop_polysyllabic`, `vocab_sophistication`. Returns a numeric matrix, one row per document. |

### Distance primitives

| Function | Signature | Purpose |
|---|---|---|
| `mahalanobis_sq()` | `mahalanobis_sq(x, center, chol_cov)` | Squared Mahalanobis distance computed via a Cholesky factor (`backsolve()`) rather than an explicit matrix inverse. |
| `cosine_sim()` | `cosine_sim(x, y)` | Cosine similarity in `[-1, 1]`, clamped to guard against `acos()` receiving a value fractionally above 1 from floating-point error. |
| `angular_dist()` | `angular_dist(x, y)` | `acos(cosine_sim(x, y)) / pi`. A true metric (satisfies the triangle inequality), unlike `1 - cosine similarity`. |

### OO workflow

| Function | Signature | Purpose |
|---|---|---|
| `build_profile()` | `build_profile(x, shrink = 0, verbose = TRUE)` | Builds a `stylo_profile` from a character vector of documents (piped through `stylo_features()`) or a numeric feature matrix. `shrink` in `[0, 1)` shrinks the sample covariance toward a scaled identity matrix. |
| `score()` | `score(x, profile, method = c("mahalanobis", "angular"))` | Scores new documents against a profile, returns a `stylo_score`. |

### Syllable counting

| Function | Signature | Purpose |
|---|---|---|
| `count_syllables_cpp()` | `count_syllables_cpp(words)` | Compiled syllable counter (C++, via Rcpp). |
| `count_syllables_r()` | `count_syllables_r(words)` | Pure R implementation of the same algorithm; exists to serve as the test oracle for the compiled version. |

### Bundled data

`lidar_reference` (245 abstracts, IEEE JSTARS lidar articles, 2008-2022) and `lidar_contrast` (211
abstracts, same journal, 2023 onward) -- both retrieved from OpenAlex, CC0 licensed, documented in
`R/data.R`.

---

## 4. How to verify

### 4.1 Automated checks

```r
devtools::test()
# or
testthat::test_local()
```

Expected result: **`[ FAIL 0 | WARN 0 | SKIP 0 | PASS 142 ]`**, broken down as:

| File | Covers | Expectations |
|---|---|---|
| `test-angular.R` | `cosine_sim()`, `angular_dist()` | 21 |
| `test-corpus.R` | corpus filter/parsing, bundled data | 35 |
| `test-mahalanobis.R` | `mahalanobis_sq()` | 22 |
| `test-profile.R` | `build_profile()`, `score()`, S3 methods | 38 |
| `test-syllables.R` | `count_syllables_cpp()` / `count_syllables_r()` | 26 |

No test in the suite touches the network -- `read_corpus_json()` is tested against the bundled
`inst/extdata/openalex_sample.json` fixture, and `fetch_corpus()` itself (the only function that makes
live HTTP calls) is deliberately left untested by the automated suite for that reason.

Also run:

```r
devtools::check()
```

Expected result: **0 errors, 0 warnings, 0 notes**.

### 4.2 Manual checks 

Each row below is a specific malformed input and the exact error message the function should raise.

| Function | Malformed input to try | Expected error (verbatim) |
|---|---|---|
| `cosine_sim(x, y)` | `y` with wrong length | `` `y` has length %d but `x` has %d columns. `` |
| `cosine_sim(x, y)` | `x` or `y` containing `NA` | `` `x` and `y` must not contain missing values. `` |
| `cosine_sim(x, y)` | `y = numeric(0)` | `` `y` has zero length; the angle is undefined. `` |
| `build_oa_filter()` | `from` later than `to` | `` `from` (%s) must be before `to` (%s). `` |
| `build_oa_filter()` | a date like `"30-11-2022"` | `` `%s` is not a date in YYYY-MM-DD form: "%s". `` (R's own `as.Date` would otherwise silently accept this) |
| `read_corpus_json()` | a path that does not exist | `no such file: "%s".` |
| `fetch_corpus()` | `max_n = -5` or `max_n = "ten"` | `` `max_n` must be a single positive number. `` |
| `stylo_features()` | `text = character(0)` | `` `text` must contain at least one document. `` |
| `stylo_features()` | `text = c("", "a word")` | No error -- the empty document returns a row of `NA`, dropped later by `build_profile()` with a message. Worth confirming it does *not* error or propagate a silent zero. |
| `mahalanobis_sq()` | a non-square `chol_cov` | `` `chol_cov` must be square. `` |
| `mahalanobis_sq()` | a singular Cholesky factor (a zero on the diagonal) | `` `chol_cov` is singular; the covariance is not positive definite. `` |
| `build_profile()` | `shrink = 1.5` or `shrink = -0.2` | `` `shrink` must be a single number in [0, 1). `` |
| `build_profile()` | fewer documents than features (e.g. 3 documents, 5 features) | `need more documents (%d) than features (%d) to estimate a covariance.` |
| `score()` | `method = "euclidean"` | base R's own `match.arg` failure, matching the pattern `"should be one of"` |
| `score()` | `profile` = anything that isn't a `stylo_profile` (e.g. a list or `NULL`) | `` `profile` must be a stylo_profile from build_profile(). `` |
| `score()` | documents with a different number of features than the profile was built on | `` `x` has %d columns but the profile was built on %d features. `` |
| `count_syllables_r()` | a numeric vector instead of character | `` `words` must be a character vector. `` |
| **`count_syllables_cpp()`** | **a list, factor, or numeric vector** | **No validation exists in the C++ layer at all** (unlike `count_syllables_r()`). This is the single best target in the package for finding an unhandled error or a crash -- it is flagged here deliberately rather than hidden. |

A good end-to-end manual check beyond single-function probes: run the Section 1 smoke test, then rebuild
`profile <- build_profile(lidar_reference$abstract, shrink = 0.1)` and confirm
`summary(profile)$condition` drops noticeably relative to `shrink = 0` (reported in the README as
~1.8x10^5 unshrunk, ~46 shrunk) -- this exercises covariance estimation on real, not synthetic, data.

---

## 5. Known limitations and assumptions

- **No `plot()` methods yet.** The original design proposal specified `print`, `summary` and `plot` for
  both S3 classes. Only `print` and `summary` exist (see `NAMESPACE`); `plot.stylo_profile` and
  `plot.stylo_score` are not implemented.
- **No vignette.** `knitr` and `rmarkdown` are listed in `DESCRIPTION`'s `Suggests` field, but there is no
  `vignettes/` directory and no `VignetteBuilder` field, so they are currently unused.
- **`stylo_features()` has no dedicated unit test file.** It is exercised only indirectly, inside
  `test-corpus.R` (one test on a parsed real abstract) and through the numeric-matrix path of
  `test-profile.R`/`test-mahalanobis.R`. A `test-features.R` pinning hand-computed values on a fixed set
  of documents is planned but not yet written.
- **The spell-check / minor-error-rate feature described in the design proposal is deferred.** It needs
  the `hunspell` package and a system dictionary; the package currently has no dependency beyond `Rcpp`,
  `stats`, `jsonlite`, `tools` and `utils`.
- **`lidar_contrast` is not a labelled dataset.** It is split from `lidar_reference` by publication date
  (2023 onward vs. up to 2022), not by whether a document is human- or machine-authored. Any result
  comparing the two corpora is a distributional-shift finding across time, not a measure of detection
  accuracy, and should not be read as one.
- **Two of the five features correlate with English proficiency and education.** `vocab_sophistication`
  and `mean_sentence_length` can flag a non-native English speaker writing ordinary prose as unusual
  relative to a reference profile built from native, highly educated writers. This is a first-order
  fairness concern carried over from the design proposal (see Fröhling & Zubiaga, 2021) and is why the
  package reports a document as a *statistical outlier*, never as "likely machine-generated."
- **`count_syllables_cpp()` performs no input validation.** Malformed input reaches Rcpp's own type
  coercion rather than a package-specific error (see Section 4.2).

---

## 6. References

Fröhling, L., & Zubiaga, A. (2021). Feature-based detection of automated language models: Tackling
GPT-2, GPT-3 and Grover. *PeerJ Computer Science*, 7, e443.

Mahalanobis, P. C. (1936). On the generalised distance in statistics. *Proceedings of the National
Institute of Sciences of India*, 2(1), 49-55.

Priem, J., Piwowar, H., & Orr, R. (2022). OpenAlex: A fully-open index of scholarly works, authors,
venues, institutions, and concepts. *arXiv:2205.01833*.

Salton, G., Wong, A., & Yang, C. S. (1975). A vector space model for automatic indexing.
*Communications of the ACM*, 18(11), 613-620.

van Dongen, S., & Enright, A. J. (2012). Metric distances derived from cosine similarity and Pearson
and Spearman correlations. *arXiv:1208.3145*.
