# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count syllables in words (compiled implementation)
#'
#' Compiled equivalent of [count_syllables_r()], using the same vowel-group
#' heuristic with the same silent-"e" and syllabic-"-le" rules. The two
#' functions must agree on every input; the unit tests enforce this by
#' differential testing.
#'
#' Syllable counting is a character-by-character scan over every word of every
#' document, which is the shape of problem where R's vectorisation gives
#' nothing and the interpreter overhead dominates. Moving the inner loop to
#' C++ removes that overhead; see the package vignette for a benchmark.
#'
#' @param words Character vector of words.
#'
#' @return Integer vector of syllable counts, the same length as `words`.
#'   Words with no alphabetic characters give 0; any other word gives at
#'   least 1. `NA` input gives `NA_integer_`.
#'
#' @examples
#' count_syllables_cpp(c("cat", "table", "beautiful"))
#'
#' @seealso [count_syllables_r()] for the reference R implementation.
#' @export
count_syllables_cpp <- function(words) {
    .Call(`_styloprofile_count_syllables_cpp`, words)
}

