# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count syllables in words (C++ version)
#'
#' Same algorithm as [count_syllables_r()], moved to C++ because it is a
#' character-by-character scan over every word of every document, which is
#' where R's interpreter overhead hurts most. Around 14x faster.
#'
#' @param words Character vector of words.
#'
#' @return Integer vector of syllable counts, same length as `words`. Words
#'   with no letters give 0, anything else gives at least 1, `NA` gives `NA`.
#'
#' @examples
#' count_syllables_cpp(c("cat", "table", "beautiful"))
#'
#' @seealso [count_syllables_r()]
#' @export
count_syllables_cpp <- function(words) {
    .Call(`_styloprofile_count_syllables_cpp`, words)
}

